/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace Crowdfunding {
      
    export type CampaignStruct = {id: BigNumberish, creator: AddressLike, title: string, description: string, goal: BigNumberish, deadline: BigNumberish, amountRaised: BigNumberish, withdrawn: boolean, exists: boolean}

    export type CampaignStructOutput = [id: bigint, creator: string, title: string, description: string, goal: bigint, deadline: bigint, amountRaised: bigint, withdrawn: boolean, exists: boolean] & {id: bigint, creator: string, title: string, description: string, goal: bigint, deadline: bigint, amountRaised: bigint, withdrawn: boolean, exists: boolean }
  
    }

  export interface CrowdfundingInterface extends Interface {
    getFunction(nameOrSignature: "campaignCount" | "contributions" | "createCampaign" | "fundCampaign" | "getCampaign" | "getCampaigns" | "refund" | "withdrawFunds"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CampaignCreated" | "Funded" | "Refunded" | "Withdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'campaignCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'contributions', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'createCampaign', values: [string, string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'fundCampaign', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCampaign', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCampaigns', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'refund', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawFunds', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'campaignCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contributions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCampaigns', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFunds', data: BytesLike): Result;
  }

  
    export namespace CampaignCreatedEvent {
      export type InputTuple = [id: BigNumberish, creator: AddressLike, title: string, goal: BigNumberish, deadline: BigNumberish];
      export type OutputTuple = [id: bigint, creator: string, title: string, goal: bigint, deadline: bigint];
      export interface OutputObject {id: bigint, creator: string, title: string, goal: bigint, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundedEvent {
      export type InputTuple = [campaignId: BigNumberish, contributor: AddressLike, amount: BigNumberish];
      export type OutputTuple = [campaignId: bigint, contributor: string, amount: bigint];
      export interface OutputObject {campaignId: bigint, contributor: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RefundedEvent {
      export type InputTuple = [campaignId: BigNumberish, contributor: AddressLike, amount: BigNumberish];
      export type OutputTuple = [campaignId: bigint, contributor: string, amount: bigint];
      export interface OutputObject {campaignId: bigint, contributor: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnEvent {
      export type InputTuple = [campaignId: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [campaignId: bigint, amount: bigint];
      export interface OutputObject {campaignId: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Crowdfunding extends BaseContract {
    
    connect(runner?: ContractRunner | null): Crowdfunding;
    waitForDeployment(): Promise<this>;

    interface: CrowdfundingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    campaignCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    contributions: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    createCampaign: TypedContractMethod<
      [_title: string, _description: string, _goal: BigNumberish, _duration: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    fundCampaign: TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    getCampaign: TypedContractMethod<
      [_id: BigNumberish, ],
      [Crowdfunding.CampaignStructOutput],
      'view'
    >
    

    
    getCampaigns: TypedContractMethod<
      [startId: BigNumberish, limit: BigNumberish, ],
      [Crowdfunding.CampaignStructOutput[]],
      'view'
    >
    

    
    refund: TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawFunds: TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'campaignCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'contributions'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createCampaign'): TypedContractMethod<
      [_title: string, _description: string, _goal: BigNumberish, _duration: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fundCampaign'): TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'getCampaign'): TypedContractMethod<
      [_id: BigNumberish, ],
      [Crowdfunding.CampaignStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getCampaigns'): TypedContractMethod<
      [startId: BigNumberish, limit: BigNumberish, ],
      [Crowdfunding.CampaignStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'refund'): TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawFunds'): TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CampaignCreated'): TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
getEvent(key: 'Funded'): TypedContractEvent<FundedEvent.InputTuple, FundedEvent.OutputTuple, FundedEvent.OutputObject>;
getEvent(key: 'Refunded'): TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
getEvent(key: 'Withdrawn'): TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;

    filters: {
      
      'CampaignCreated(uint256,address,string,uint256,uint256)': TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
      CampaignCreated: TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
    

      'Funded(uint256,address,uint256)': TypedContractEvent<FundedEvent.InputTuple, FundedEvent.OutputTuple, FundedEvent.OutputObject>;
      Funded: TypedContractEvent<FundedEvent.InputTuple, FundedEvent.OutputTuple, FundedEvent.OutputObject>;
    

      'Refunded(uint256,address,uint256)': TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
      Refunded: TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
    

      'Withdrawn(uint256,uint256)': TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
      Withdrawn: TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
    
    };
  }